/// 球隊英文名稱 → 繁體中文名稱對照表
/// 覆蓋：MLB、NBA、英超、英冠、西甲、德甲、意甲、法甲、荷甲等主流聯賽
class TeamNameService {
  TeamNameService._();

  static String translate(String name) {
    if (name.isEmpty) return name;
    final key = name.trim();
    return _map[key] ?? _map[key.toLowerCase()] ?? _partialMatch(key) ?? key;
  }

  /// 部分比對（用於 shortName 如 "Man City" → 曼城）
  static String? _partialMatch(String name) {
    final lower = name.toLowerCase();
    for (final entry in _map.entries) {
      if (entry.key.toLowerCase() == lower) return entry.value;
    }
    // 嘗試包含比對（shortName 可能是 full name 的一部分）
    for (final entry in _map.entries) {
      final k = entry.key.toLowerCase();
      if (k.contains(lower) || lower.contains(k)) {
        if (k.length > 3 && lower.length > 3) return entry.value;
      }
    }
    return null;
  }

  static const _map = <String, String>{
    // ── MLB 美職棒 ──────────────────────────────────────────────────
    'Arizona Diamondbacks': '亞利桑那響尾蛇',
    'Arizona': '亞利桑那',
    'Atlanta Braves': '亞特蘭大勇士',
    'Baltimore Orioles': '巴爾的摩金鶯',
    'Boston Red Sox': '波士頓紅襪',
    'Chicago Cubs': '芝加哥小熊',
    'Chicago White Sox': '芝加哥白襪',
    'Cincinnati Reds': '辛辛那提紅人',
    'Cleveland Guardians': '克里夫蘭守護者',
    'Colorado Rockies': '科羅拉多洛磯',
    'Detroit Tigers': '底特律老虎',
    'Houston Astros': '休士頓太空人',
    'Kansas City Royals': '堪薩斯市皇家',
    'Los Angeles Angels': '洛杉磯天使',
    'Los Angeles Dodgers': '洛杉磯道奇',
    'Miami Marlins': '邁阿密馬林魚',
    'Milwaukee Brewers': '密爾瓦基釀酒人',
    'Minnesota Twins': '明尼蘇達雙城',
    'New York Mets': '紐約大都會',
    'New York Yankees': '紐約洋基',
    'Oakland Athletics': '奧克蘭運動家',
    'Sacramento Athletics': '沙加緬度運動家',
    'Philadelphia Phillies': '費城費城人',
    'Pittsburgh Pirates': '匹茲堡海盜',
    'San Diego Padres': '聖地牙哥教士',
    'San Francisco Giants': '舊金山巨人',
    'Seattle Mariners': '西雅圖水手',
    'St. Louis Cardinals': '聖路易紅雀',
    'Tampa Bay Rays': '坦帕灣光芒',
    'Texas Rangers': '德州遊騎兵',
    'Toronto Blue Jays': '多倫多藍鳥',
    'Washington Nationals': '華盛頓國民',
    // shortNames
    'Diamondbacks': '響尾蛇',
    'Braves': '勇士',
    'Orioles': '金鶯',
    'Red Sox': '紅襪',
    'Cubs': '小熊',
    'White Sox': '白襪',
    'Reds': '紅人',
    'Guardians': '守護者',
    'Rockies': '洛磯',
    'Tigers': '老虎',
    'Astros': '太空人',
    'Royals': '皇家',
    'Angels': '天使',
    'Dodgers': '道奇',
    'Marlins': '馬林魚',
    'Brewers': '釀酒人',
    'Twins': '雙城',
    'Mets': '大都會',
    'Yankees': '洋基',
    'Athletics': '運動家',
    'A\'s': '運動家',
    'Phillies': '費城人',
    'Pirates': '海盜',
    'Padres': '教士',
    'Giants': '巨人',
    'Mariners': '水手',
    'Cardinals': '紅雀',
    'Rays': '光芒',
    'Rangers': '遊騎兵',
    'Blue Jays': '藍鳥',
    'Nationals': '國民',
    // ── NBA ─────────────────────────────────────────────────────────
    'Atlanta Hawks': '亞特蘭大老鷹',
    'Boston Celtics': '波士頓賽爾提克',
    'Brooklyn Nets': '布魯克林籃網',
    'Charlotte Hornets': '夏洛特黃蜂',
    'Chicago Bulls': '芝加哥公牛',
    'Cleveland Cavaliers': '克里夫蘭騎士',
    'Dallas Mavericks': '達拉斯獨行俠',
    'Denver Nuggets': '丹佛金塊',
    'Detroit Pistons': '底特律活塞',
    'Golden State Warriors': '金州勇士',
    'Houston Rockets': '休士頓火箭',
    'Indiana Pacers': '印第安納溜馬',
    'LA Clippers': '洛杉磯快艇',
    'Los Angeles Clippers': '洛杉磯快艇',
    'LA Lakers': '洛杉磯湖人',
    'Los Angeles Lakers': '洛杉磯湖人',
    'Memphis Grizzlies': '曼菲斯灰熊',
    'Miami Heat': '邁阿密熱火',
    'Milwaukee Bucks': '密爾瓦基公鹿',
    'Minnesota Timberwolves': '明尼蘇達森林狼',
    'New Orleans Pelicans': '紐奧良鵜鶘',
    'New York Knicks': '紐約尼克',
    'Oklahoma City Thunder': '奧克拉荷馬雷霆',
    'Orlando Magic': '奧蘭多魔術',
    'Philadelphia 76ers': '費城76人',
    'Phoenix Suns': '鳳凰城太陽',
    'Portland Trail Blazers': '波特蘭拓荒者',
    'Sacramento Kings': '沙加緬度國王',
    'San Antonio Spurs': '聖安東尼奧馬刺',
    'Toronto Raptors': '多倫多暴龍',
    'Utah Jazz': '猶他爵士',
    'Washington Wizards': '華盛頓巫師',
    // shortNames
    'Hawks': '老鷹',
    'Celtics': '賽爾提克',
    'Nets': '籃網',
    'Hornets': '黃蜂',
    'Bulls': '公牛',
    'Cavaliers': '騎士',
    'Cavs': '騎士',
    'Mavericks': '獨行俠',
    'Mavs': '獨行俠',
    'Nuggets': '金塊',
    'Pistons': '活塞',
    'Warriors': '勇士',
    'Rockets': '火箭',
    'Pacers': '溜馬',
    'Clippers': '快艇',
    'Lakers': '湖人',
    'Grizzlies': '灰熊',
    'Heat': '熱火',
    'Bucks': '公鹿',
    'Timberwolves': '森林狼',
    'Wolves': '森林狼',
    'Pelicans': '鵜鶘',
    'Knicks': '尼克',
    'Thunder': '雷霆',
    'Magic': '魔術',
    '76ers': '76人',
    'Sixers': '76人',
    'Suns': '太陽',
    'Blazers': '拓荒者',
    'Kings': '國王',
    'Spurs': '馬刺',
    'Raptors': '暴龍',
    'Jazz': '爵士',
    'Wizards': '巫師',
    // ── 英超 EPL ────────────────────────────────────────────────────
    'Arsenal': '兵工廠',
    'Aston Villa': '阿斯頓維拉',
    'Bournemouth': '波茅斯',
    'Brentford': '賓福特',
    'Brighton': '布萊頓',
    'Brighton & Hove Albion': '布萊頓',
    'Chelsea': '車路士',
    'Crystal Palace': '水晶宮',
    'Everton': '愛華頓',
    'Fulham': '富勒姆',
    'Ipswich': '伊普斯維奇',
    'Ipswich Town': '伊普斯維奇',
    'Leicester': '萊斯特城',
    'Leicester City': '萊斯特城',
    'Liverpool': '利物浦',
    'Man City': '曼城',
    'Manchester City': '曼城',
    'Man United': '曼聯',
    'Manchester United': '曼聯',
    'Newcastle': '紐卡素',
    'Newcastle United': '紐卡素',
    'Nottm Forest': '諾定咸森林',
    'Nottingham Forest': '諾定咸森林',
    'Southampton': '修咸頓',
    'Tottenham': '熱刺',
    'Tottenham Hotspur': '熱刺',
    'West Ham': '韋斯咸',
    'West Ham United': '韋斯咸',
    'Wolverhampton': '狼隊',
    'Wolverhampton Wanderers': '狼隊',
    // ── 英冠 Championship ──────────────────────────────────────────
    'Burnley': '伯恩利',
    'Cardiff': '卡迪夫',
    'Cardiff City': '卡迪夫城',
    'Coventry': '高雲地利',
    'Coventry City': '高雲地利',
    'Derby': '德比',
    'Derby County': '德比郡',
    'Huddersfield': '哈德斯菲爾德',
    'Huddersfield Town': '哈德斯菲爾德',
    'Hull': '赫爾城',
    'Hull City': '赫爾城',
    'Leeds': '里茲聯',
    'Leeds United': '里茲聯',
    'Luton': '盧頓',
    'Luton Town': '盧頓',
    'Middlesbrough': '米德斯堡',
    'Millwall': '米爾沃爾',
    'Norwich': '諾里奇',
    'Norwich City': '諾里奇',
    'Plymouth': '普利茅斯',
    'Plymouth Argyle': '普利茅斯',
    'Preston': '普雷斯頓',
    'Preston North End': '普雷斯頓',
    'QPR': '昆士柏流浪',
    'Queens Park Rangers': '昆士柏流浪',
    'Reading': '雷丁',
    'Rotherham': '羅瑟哈姆',
    'Rotherham United': '羅瑟哈姆',
    'Sheffield United': '謝菲爾德聯',
    'Sheffield Wednesday': '謝菲爾德星期三',
    'Sheffield': '謝菲爾德',
    'Stoke': '斯托克',
    'Stoke City': '斯托克',
    'Sunderland': '桑德蘭',
    'Swansea': '斯旺西',
    'Swansea City': '斯旺西',
    'Watford': '沃特福德',
    'West Brom': '西布朗',
    'West Bromwich Albion': '西布朗',
    'Blackburn': '布力般流浪',
    'Blackburn Rovers': '布力般流浪',
    'Bristol City': '布里斯托城',
    'Oxford United': '牛津聯',
    'Portsmouth': '樸茨茅斯',
    // ── 西甲 La Liga ───────────────────────────────────────────────
    'Athletic Bilbao': '畢爾包',
    'Athletic Club': '畢爾包',
    'Atletico Madrid': '馬德里體育會',
    'Atlético Madrid': '馬德里體育會',
    'Atlético de Madrid': '馬德里體育會',
    'Barcelona': '巴塞隆拿',
    'Betis': '貝蒂斯',
    'Real Betis': '皇家貝蒂斯',
    'Celta Vigo': '塞爾達',
    'Celta de Vigo': '塞爾達',
    'Espanyol': '西班牙人',
    'RCD Espanyol': '西班牙人',
    'Getafe': '赫達菲',
    'Girona': '希羅納',
    'Granada': '格拉納達',
    'Leganes': '萊加內斯',
    'Leganés': '萊加內斯',
    'Mallorca': '馬略卡',
    'RCD Mallorca': '馬略卡',
    'Osasuna': '奧薩蘇納',
    'CA Osasuna': '奧薩蘇納',
    'Rayo Vallecano': '萊亞利加諾',
    'Real Madrid': '皇家馬德里',
    'Real Sociedad': '皇家蘇斯達',
    'Sevilla': '西維爾',
    'Sevilla FC': '西維爾',
    'Valencia': '華倫西亞',
    'Valencia CF': '華倫西亞',
    'Valladolid': '瓦拉多利',
    'Real Valladolid': '瓦拉多利',
    'Villarreal': '比利亞雷亞爾',
    'Villarreal CF': '比利亞雷亞爾',
    'Alaves': '阿拉維斯',
    'Deportivo Alavés': '阿拉維斯',
    'Las Palmas': '帕爾馬斯',
    'UD Las Palmas': '帕爾馬斯',
    // ── 德甲 Bundesliga ─────────────────────────────────────────────
    'Augsburg': '奧格斯堡',
    'FC Augsburg': '奧格斯堡',
    'Bayer Leverkusen': '勒沃庫森',
    'Leverkusen': '勒沃庫森',
    'Bayern Munich': '拜仁慕尼黑',
    'FC Bayern München': '拜仁慕尼黑',
    'Bayern München': '拜仁慕尼黑',
    'Bochum': '波鴻',
    'VfL Bochum': '波鴻',
    'Borussia Dortmund': '多特蒙德',
    'Dortmund': '多特蒙德',
    'Borussia Mönchengladbach': '門興格拉德巴赫',
    'Mönchengladbach': '門興格拉德巴赫',
    'Gladbach': '門興格拉德巴赫',
    'Eintracht Frankfurt': '法蘭克福',
    'Frankfurt': '法蘭克福',
    'Freiburg': '弗萊堡',
    'SC Freiburg': '弗萊堡',
    'Hamburger SV': '漢堡',
    'Hamburg': '漢堡',
    'Heidenheim': '海登海姆',
    '1. FC Heidenheim': '海登海姆',
    'Hoffenheim': '霍芬海姆',
    'TSG Hoffenheim': '霍芬海姆',
    'Cologne': '科隆',
    '1. FC Köln': '科隆',
    'RB Leipzig': '萊比錫',
    'Leipzig': '萊比錫',
    'Mainz': '美因茨',
    '1. FSV Mainz 05': '美因茨',
    'Schalke': '沙爾克',
    'FC Schalke 04': '沙爾克',
    'Stuttgart': '斯圖加特',
    'VfB Stuttgart': '斯圖加特',
    'Union Berlin': '聯合柏林',
    '1. FC Union Berlin': '聯合柏林',
    'Werder Bremen': '不來梅',
    'Bremen': '不來梅',
    'Wolfsburg': '沃爾夫斯堡',
    'VfL Wolfsburg': '沃爾夫斯堡',
    'St. Pauli': '聖保利',
    'FC St. Pauli': '聖保利',
    'Holstein Kiel': '基爾',
    // ── 意甲 Serie A ────────────────────────────────────────────────
    'AC Milan': 'AC米蘭',
    'Milan': 'AC米蘭',
    'AS Roma': '羅馬',
    'Roma': '羅馬',
    'Atalanta': '亞特蘭大',
    'Torino': '都靈',
    'FC Torino': '都靈',
    'Cagliari': '卡利亞里',
    'Empoli': '恩波利',
    'Fiorentina': '費倫提納',
    'ACF Fiorentina': '費倫提納',
    'Frosinone': '弗羅西諾內',
    'Genoa': '熱那亞',
    'Inter Milan': '國際米蘭',
    'Inter': '國際米蘭',
    'FC Internazionale': '國際米蘭',
    'Internazionale': '國際米蘭',
    'Juventus': '尤文圖斯',
    'Lazio': '拉齊奧',
    'SS Lazio': '拉齊奧',
    'Lecce': '萊切',
    'US Lecce': '萊切',
    'Monza': '蒙扎',
    'Napoli': '拿坡里',
    'SSC Napoli': '拿坡里',
    'Parma': '帕爾馬',
    'Salernitana': '薩勒尼塔納',
    'US Salernitana': '薩勒尼塔納',
    'Sampdoria': '桑普多利亞',
    'UC Sampdoria': '桑普多利亞',
    'Sassuolo': '薩索羅',
    'US Sassuolo': '薩索羅',
    'Udinese': '烏迪內塞',
    'Venezia': '威尼斯',
    'Hellas Verona': '維羅納',
    'Verona': '維羅納',
    'Bologna': '波隆那',
    'Como': '科莫',
    // ── 法甲 Ligue 1 ────────────────────────────────────────────────
    'Brest': '布雷斯特',
    'Stade Brestois 29': '布雷斯特',
    'Lens': '朗斯',
    'RC Lens': '朗斯',
    'Lille': '里爾',
    'LOSC Lille': '里爾',
    'Lyon': '里昂',
    'Olympique Lyonnais': '里昂',
    'Marseille': '馬賽',
    'Olympique de Marseille': '馬賽',
    'Monaco': '摩納哥',
    'AS Monaco': '摩納哥',
    'Montpellier': '蒙彼利埃',
    'Nantes': '南特',
    'FC Nantes': '南特',
    'Nice': '尼斯',
    'OGC Nice': '尼斯',
    'Paris Saint-Germain': '巴黎聖日耳曼',
    'PSG': '巴黎聖日耳曼',
    'Rennes': '雷恩',
    'Stade Rennais': '雷恩',
    'Strasbourg': '斯特拉斯堡',
    'RC Strasbourg': '斯特拉斯堡',
    'Toulouse': '土魯斯',
    'Toulouse FC': '土魯斯',
    'Reims': '蘭斯',
    'Stade de Reims': '蘭斯',
    'Le Havre': '勒阿弗爾',
    'Metz': '梅斯',
    'Lorient': '洛里昂',
    'Angers': '昂熱',
    'Auxerre': '歐塞爾',
    'Saint-Étienne': '聖艾蒂安',
    // ── 荷甲 Eredivisie ─────────────────────────────────────────────
    'Ajax': '阿賈克斯',
    'AZ Alkmaar': '阿爾克馬爾',
    'AZ': '阿爾克馬爾',
    'Feyenoord': '費耶諾德',
    'PSV': '埃因霍溫',
    'PSV Eindhoven': '埃因霍溫',
    'Utrecht': '烏特勒支',
    'FC Utrecht': '烏特勒支',
    'Twente': '圖文特',
    'FC Twente': '圖文特',
    'Heerenveen': '赫倫芬',
    'SC Heerenveen': '赫倫芬',
    'Vitesse': '維特斯',
    'Sparta Rotterdam': '鹿特丹斯巴達',
    'Go Ahead Eagles': '鷹隊',
    'Almere City': '阿爾梅勒城',
    'RKC Waalwijk': '瓦爾維克',
    'NEC Nijmegen': '奈梅亨',
    'Groningen': '格羅寧根',
    'Cambuur': '坎布爾',
    'Excelsior': '埃克塞爾西奧',
    'PEC Zwolle': '茲沃勒',
    'Willem II': '威廉二世',
    'NAC Breda': '布雷達',
    // ── 葡超 Primeira Liga ──────────────────────────────────────────
    'Benfica': '本菲卡',
    'SL Benfica': '本菲卡',
    'Braga': '布拉加',
    'SC Braga': '布拉加',
    'Porto': '波圖',
    'FC Porto': '波圖',
    'Sporting CP': '體育里斯本',
    'Sporting': '體育里斯本',
    'Vitória SC': '維托里亞',
    'Rio Ave': '里奧阿維',
    'Famalicão': '法馬利康',
    // ── 歐冠 Champions League ────────────────────────────────────────
    // (團隊名稱已在各聯賽中涵蓋)
    // ── 瑞典甲 Allsvenskan ──────────────────────────────────────────
    'AIK': '艾克',
    'Djurgarden': '尤加登',
    'Djurgårdens IF': '尤加登',
    'Hammarby': '漢馬比',
    'Malmo': '馬爾默',
    'Malmö FF': '馬爾默',
    'IFK Gothenburg': '哥特堡',
    'IFK Göteborg': '哥特堡',
    'Goteborg': '哥特堡',
    'Goteborg IF': '哥特堡',
    'Häcken': '哈肯',
    'BK Häcken': '哈肯',
    'Elfsborg': '艾爾夫斯博格',
    'IF Elfsborg': '艾爾夫斯博格',
    'Brommapojkarna': '布朗納波卡納',
    'IFK Norrköping': '諾爾雪平',
    'Norrkoping': '諾爾雪平',
    'Kalmar FF': '卡爾馬',
    'Sirius': '錫里烏斯',
    'IK Sirius': '錫里烏斯',
    'Degerfors': '德格弗斯',
  };
}
